### ISSUE TITLE
Editor takes too much time when base directory has many directories

### ISSUE THREAD

**Issue by eddumelendez** [atomist-attic/rug-cli#106]
Running one of the editors located at https://github.com/eddumelendez/spring-boot-rugs is taking too much time and sometimes get StackOverflow when the base directory contains lot of directories but when the base directory is empty or contains few directories, editor performs very well

**Comment by cdupuis** [comment]
Thanks @eddumelendez for the report. How can I re-create this problem? Do you have a command line I could run?

**Comment by eddumelendez** [comment]
I have 245 directories. In order to reproduce the problem download the rugs from [here](https://github.com/eddumelendez/spring-boot-rugs) and install them, then run the command below

```
rug edit eddumelendez:spring-boot-rugs:NewSpringBootJavaMavenProject project_base_directory=bootrug
```

**Comment by cdupuis** [comment]
Thanks for this. What is `bootrug`? Is that a special folder on your hard drive?

**Comment by eddumelendez** [comment]
`bootrug` is the folder name where my default project will be created

**Comment by cdupuis** [comment]
Why are you running an editor to create a project? Isn't that a generator use-case.

Sorry, for asking again, but those 245 dirs, where are they? In the folder denoted by `bootrug`?

**Comment by eddumelendez** [comment]
I've been following the approach from [atomist-rugs/spring-boot-editors](https://github.com/atomist-rugs/spring-boot-editors/)

In order to provide my steps and having the following directory structure:

```
repositories
- demo1
- demo2
```

Scenario 1:
. Locate inside `repositories` folder
. Create empty `bootrug` folder
. Apply editor `atomist-rugs:spring-boot-editors:AddSpringBootProjectToExistingProject` with param `project_base_directory=bootrug`
. Result: SUCCESS

Scenario 2:
. Locate inside `repositories` folder
. Apply editor `atomist-rugs:spring-boot-editors:AddSpringBootProjectToExistingProject` with param `project_base_directory=bootrug`
. Result: SUCCESS
(*) `bootrug` directory is created

But, if there are many folder in the parent directory let say inside `repositories`

Scenario 1:
. Locate inside `repositories` folder
. Create empty `bootrug` folder
. Apply editor `atomist-rugs:spring-boot-editors:AddSpringBootProjectToExistingProject` with param `project_base_directory=bootrug`
. Result: FAIL

Scenario 2:
. Locate inside `repositories` folder
. Apply editor `atomist-rugs:spring-boot-editors:AddSpringBootProjectToExistingProject` with param `project_base_directory=bootrug`
. Result: FAIL
(*) It takes too much time and when some logs appear, it is stopped suddenly

```
 % rug edit atomist-rugs:spring-boot-editors:AddSpringBootProjectToExistingProject project_base_directory=bootrug                                                            !11226
Resolving dependencies for atomist-rugs:spring-boot-editors:latest completed
Loading atomist-rugs:spring-boot-editors:0.5.3 into runtime completed
Running editor AddSpringBootProjectToExistingProject of atomist-rugs:spring-boot-editors:0.5.3 completed

→ Project
```

(*) Just once I got a `StackOverflowError`

**Comment by cdupuis** [comment]
@alankstewart that sounds like a problem with the `ArtifactSource` implementation really. Can you take a look and maybe try to re-create this?

**Comment by alankstewart** [comment]
@eddumelendez as agreed on Atomist community channel, will wait to you move to TypeScript and attempt to reproduce
