### ISSUE TITLE
rug login does not work with GitHub passwords containing special characters

### ISSUE THREAD

**Issue by donovanmuller** [atomist-attic/rug-cli#219]
This issue is a little difficult to give a complete example of 😉  but basically if your GitHub password contains certain special characters, let's say one/combination of these `!/\[];',@#$%^&`, then login fails.

I changed my password to not contain any of these characters and then was able to login successfully. I'm assuming some escaping needs to be done on the password input?

I'm using `zsh` with [oh my zsh](https://github.com/robbyrussell/oh-my-zsh) in iTerm2 if that helps.

**Comment by cdupuis** [comment]
Oh, thanks @donovanmuller.

There is a simple work-around for this which doesn't require you to change your password: You can manually create a personal access token on GitHub and put that into the `~/.atomist/cli.yml` at:

```
configuration:
  github_token: "0...d"
```
