### ISSUE TITLE
rug search doesn't search in operation name

### ISSUE THREAD

**Issue by tanya-coding** [atomist-attic/rug-cli#99]
For example, when running `rug search typescript` I expected to find `atomist-rugs:rug-editors` which contains an editor `atomist-rugs:rug-editors:AddTypeScript` but it wasn't returned by the search

**Comment by cdupuis** [comment]
Hmm, I see the archive being returned:

```
✔ ~/Development/atomist-rugs/scala-editors [master|✚ 1] 
18:05 $ rug search typescript
Resolving dependencies for atomist-rugs:scala-editors:0.1.0 ← local completed
  Searching https://api.atomist.com/catalog                                                                                                                                                                                                                                               
Searching catalogs completed

→ Remote Archives (2 archives found)
  atomist-rugs:rug-editors (0.6.0)
  atomist-rugs:travis-editors (0.12.2)

For more information on specific archive version, run:
  rug describe archive ARCHIVE -a VERSION
✔ ~/Development/atomist-rugs/scala-editors [master|✚ 1] ```

**Comment by tanya-coding** [comment]
It's now returned because @ddgenome just published a new version where he updated description to `adds a TypeScript supporting files to an existing Rug Archive project` so it now hits the description and finds the archive (previous version had wrong description and search wouldn't return it)

**Comment by cdupuis** [comment]
@claymccoy can we support looking at operation names too?

**Comment by claymccoy** [comment]
You can specify operation name directly. I can add it to the freetext search, but the name probably wouldn't be tokenized correctly.

**Comment by tanya-coding** [comment]
Ideally I'd like to be able to find operation with name "AddTypeScript" when I search for "typescript" or "TypeScript"

**Comment by claymccoy** [comment]
Yeah, that means that we will have to have another operation name field and a custom tokenizer that  understands camel case. It is possible, but we have to spoon feed Elasticsearch.

**Comment by ddgenome** [comment]
Can we just allow partial, case-insensitive of the operation name field?

**Comment by claymccoy** [comment]
Maybe. How is that done? Everything that I have read about ES customization involves writing a tokenizer.

**Comment by ddgenome** [comment]
I was truly just asking the question.

**Comment by ddgenome** [comment]
https://www.elastic.co/guide/en/elasticsearch/guide/current/partial-matching.html

**Comment by claymccoy** [comment]
Thanks, that is interesting. Name is an "exact-value not_analyzed" field. I'm wondering if there is a large performance impact for partial searches.

**Comment by cdupuis** [comment]
What is the latest on this here?
